### ISSUE TITLE
Q2PRO bug: blood particles can have water/slime/lava mixed in if those are traced behind them

### ISSUE THREAD

**Issue by Paril** [Paril/q2pro#101]
Have slime/lava behind the enemy under your crosshair and fire shotgun at enemy; the blood will have slime/lava mixed into it

**Comment by ghost** [comment]
I think `dst->contents |= src->contents` line should be changed to `dst->contents = src->contents` in `CM_ClipEntity()`. Don't remember why was this change done, but now it seems it was wrong as it breaks game logic.
