### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by Paril** [Paril/q2pro#4]
- [ ] RF_DOT_SHADOW
- [ ] allow entire engine to use kfonts automatically when appropriate
- [ ] ps.gunframe supports up to 512 in rr
  - [ ] the remaining bits are used to compress other elements; bits 9-15 are whether gunoffset[n]/gunangles[n]/gunrate are changed
  - [ ] gunoffset/gunangles are full float in rr, but we might be able to find something smaller. it needs to be able to maintain smooth rotation which uses fairly small values
- [ ] kick_angles are short / 1024
- [ ] viewoffset are short / 16
- [x] fix interpolation on a couple tent effects (explosions, etc)
- [x] support 96 length configstring values
- [x] bring over Steam/GoG auto-detect
- [x] embed q2pro.menu file for default behavior (allows engine to be drop-in)
- [x] fix instant packet for jump/crouch
- [x] have font shadows work conditionally (UI_DROPSHADOW is unused)
- [x] support footstep materials
- [x] localization support
- [x] support reverb effects (when OpenAL is being used) from material files
  - [ ] support `mapname.environments` additional files
  - [ ] cache defaults for entirety of AL being loaded
  - [x] figure out why OpenAL sounds so weird compared to DMA
- [x] support glowmaps
- [ ] bloom (on glowmaps only)
- [ ] support shadow-lights
- [x] support OGV videos
- [x] per-pixel lighting support for dynamic lighting
- [x] support +holster
- [x] support weapon wheel
  - [x] parse CS_ wheel data into cls
  - [x] use CS_ wheel data for warn ammo count
  - [x] support +wheel / +wheel2 (dummy button bits)
  - [x] support cl_nextweap / cl_prevweap carousel
- [x] support re-release cgame DLL protocol
  - [x] run pmove on cgame
  - [x] support re-release pmove prediction
- [x] support bot navigation nodes
  - [x] A* query
  - [x] handle flags/types
  - [ ] fix weight/heuristic
- [ ] RF_LOW_PRIORITY support (entities marked with this can be replaced in AddEntity if there are no more slots left; in Q2PRO we could also extend this to the network layer, and not sync entities with these if we run out of packet space)
- [ ] RF_NO_STEREO support (speakers marked with this flag should always be played monaural)
- [ ] RF_STAIR_STEP support (when this flag is set, the renderer should assume a 10hz interpolation between (old_origin.z - origin.z)
- [ ] RF_CUSTOM_LIGHT support (just a custom dlight)
- [x] RF_SHELL_LITE_GREEN support
- [ ] RF_FLARE_LOCK_ANGLE support (not sure if skuller nabbed this one in his flare impl yet)
- [ ] RDF_NO_WEAPON_LERP (unused but implemented in kex)
- [x] handle damage_blend and screen_blend properly (maybe with a cvar that merges them both together if users want always full screen blends)
- [x] support POIs
- [x] support screen damage indicators
- [x] support hit markers
- [x] check/fix demo recording, playback support after the protocol changes
  - [ ] properly use cgame for "rerelease" demos
- [x] check/fix old demos support after the protocol changes
- [x] check/fix MVD support after the protocol changes
- [x] support N64 skies
- [x] lightning lasers
- [ ] proper sound spatialization origins
- [ ] support SVF_INSTANCED properly
- [ ] scr_safe_zone
- [x] adjust `hud_scale/scr_scale/ui_scale 0` to be 2x at 720p
- [x] fog + heightfog support. for legacy code path, we'll have to make a bit of a compromise though.
- [x] debug draw interface
- [ ] lightstyle interpolation
- [x] kfont support
  - [ ] multi-line string draws
  - [ ] UTF-8 chars
- [x] muzzleflashes
- [x] typewriter centerprint
- [x] compass
- [x] dogtags

**Comment by res2k** [comment]
Please add:
[ ] check/fix demo recording, playback support after the protocol changes
[ ] check/fix old demos support after the protocol changes
[ ] check/fix MVD support after the protocol changes

**Comment by Paril** [comment]
Moved to individual issues
