### ISSUE TITLE
use static OpenAL

### ISSUE THREAD

**Issue by Paril** [Paril/q2pro#96]
OpenAL 1.0/1.1 sucks, the only real option people will want is oal-soft, but I don't want to introduce additional DLLs that need to be copied around.

**Comment by Paril** [comment]
can you look into this @res2k? I have it pushed up but some of the builds are weird and I dunno if it's statically linking it properly

**Comment by Paril** [comment]
seems to work, although the new ffmpeg wrap causes issues with the msvc backend; not sure if it's fixable or worth trying to fix, I just disabled avcodec for my own builds.

**Comment by res2k** [comment]
> just disabled avcodec for my own builds

Yeah. I don't have a better suggestion, either.

The msvc backend issues are probably fixable ... in meson.
But I suspect the group of people consisting of "uses meson & uses msvc backend & has the resources to work on both" is rather small, so that backend doesn't get as much attention as others.

**Comment by Paril** [comment]
Feel free to close this off if we're all good on static stuff now - unless you want to edit the code to support non-static-openal mode and add an option flag for it or something (maybe that can get merged upstream?)

code-wise the game will use the built-in OpenAL if al_driver is empty.

**Comment by res2k** [comment]
Think we're good.
