### ISSUE TITLE
mgu6m1 func_object spawns falling down

### ISSUE THREAD

**Issue by Paril** [Paril/q2pro#98]
Complete softlock in mgu6m1; there's a func_object around `1222.0 -1408.9 -1220.1` that probably wasn't meant to be a func_object (maybe they intended a func_wall or something); it's intersecting a wall, and in Kex, it doesn't fall, but for some reason in Q2PRO it falls into place blocking the entrance that you're supposed to crouch through.

Also in mgu6m2; `2757.8 956.7 -1725.0`
Also mgu4m1: 546.3 -170.0 247.0

**Comment by ghost** [comment]
This is a known issue, needs `map_allsolid_bug 0` to match Kex behavior.

**Comment by Paril** [comment]
> This is a known issue, needs `map_allsolid_bug 0` to match Kex behavior.

We actually did fix this in Kex though (it was breaking other stuff, so to match kex `map_allsolid_bug` should always be 1) - we set fraction to 0 and trace->contents to brush->contents if !getout, so I don't think it's that, it's just that that somehow also fixes the issue even though it shouldn't, heh

**Comment by Paril** [comment]
[func_object.zip](https://github.com/user-attachments/files/17633041/func_object.zip)

Made a minimal repro if you also want to play with it. I'm going to debug kex first and see if I can track down why it doesn't fall there before I step back into q2pro and figure out why it *is* falling there.

**Comment by Paril** [comment]
Oops, I just realized what you were trying to tell me skuller - that that *should* be zero, which is what follows the Kex behavior. Me idiot - thanks! I'll make that change here.
