### ISSUE TITLE
mgu6m2 missing faces

### ISSUE THREAD

**Issue by Paril** [Paril/q2pro#99]
![](https://i.imgur.com/AcAy9xs.png)
![](https://i.imgur.com/OrXs7rx.png)
2153.8 1167.7 -1492.2 -11.0 274.2 0.0

Appears to be a vis issue; this went unnoticed in Kex because of the cell-based renderer (entities disappear if shot into).
Seems like skuller tried to fix via `map_visibility_patch` but it doesn't seem to be working.

**Comment by ghost** [comment]
Checksum needs to be updated to match current version of the map.

**Comment by Paril** [comment]
Thanks! Fixed in b67a4a0cb3811b3d3069c23b2cc31c872374f59e
